### ISSUE TITLE
Include a mention to the original author

### ISSUE THREAD

**Issue by jmdaweb** [ruifontes/addonsTools#1]
Since this is a derived software based on Héctor Benítez's work, in order to meet all GPL requirements, he should be included as part of the author field in buildVars.py and readme. You might use something like "Original work by" or similar, as we do in TeleNVDA. Please, apply this change as soon as possible in this and other similar repositories if needed. 
CC: @hxebolax

**Comment by ruifontes** [comment]
Thanks José Manuel!
I normally do it...
However I have kept the copyright in the .py files...
I will place the mention in buildvars and readme in the next version...

**Comment by nvdaes** [comment]
Hi Rui. I think you should keep this issue opened until the original author is mentioned,since other authors are reflected in the readme and this is confusing.
can you address this please?
Thanks

**Comment by ruifontes** [comment]
Done.
